### PR TITLE
Akismet: Adding new service parameters

### PR DESCRIPTION
**Pull request by initvector**
Added comment_type, blog_lang and blog_charset.

Should not be merged until May 22nd at the earliest.

### CODE REVIEW

**Comment by tburry** [comment]
Can you check the history of this plugin? We made a change a while back that was similar and it caused all spam to make it through detection and was a complete nightmare.

**Comment by initvector** [comment]
52ff341ae5df5e9b25bf65ff63422aa43a6fade5 added comment_type, but set it to "forum", instead of "forum-post" as recommended [here](http://blog.akismet.com/2012/06/19/pro-tip-tell-us-your-comment_type/).

This PR sets comment_type to forum-post and only adds it for Discussion and Comment checks (the previous way tacked it onto every request).  This is in addition to adding language and charset parameters.

**Comment by tburry** [comment]
The way to role this out would be to:

1. Add a config setting, but make the plugin behave as it currently does.
2. Find a friendly forum like penny arcade and flip that setting for a day.
3. See what happens.

Trust me. We don't want spam to start flooding in by accident.

**Comment by linc** [comment]
Agreed. I have this running on my sites but that is mostly limited to vetting registrations, not posts, since my sites are approval registration. Have support identify a couple problem sites that would happily try an alternative.

**Pull request closed without merging**
